//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyFileVersion("0.13000.1206.1753")]
[assembly: System.Reflection.AssemblyInformationalVersion("2510b31b5078e693a33d5655c4920fcfd9529f54")]
[assembly: System.Reflection.AssemblyVersion("0.13000.1206.1753")]


